// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Corewar_Api/ent/champ"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Champ is the model entity for the Champ schema.
type Champ struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// NumberOfVictory holds the value of the "number_of_victory" field.
	NumberOfVictory int `json:"number_of_victory,omitempty"`
	// NumberOfDefeats holds the value of the "number_of_defeats" field.
	NumberOfDefeats int `json:"number_of_defeats,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Champ) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case champ.FieldNumberOfVictory, champ.FieldNumberOfDefeats:
			values[i] = new(sql.NullInt64)
		case champ.FieldName, champ.FieldPath:
			values[i] = new(sql.NullString)
		case champ.FieldID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Champ", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Champ fields.
func (c *Champ) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case champ.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				c.ID = *value
			}
		case champ.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		case champ.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				c.Path = value.String
			}
		case champ.FieldNumberOfVictory:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number_of_victory", values[i])
			} else if value.Valid {
				c.NumberOfVictory = int(value.Int64)
			}
		case champ.FieldNumberOfDefeats:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number_of_defeats", values[i])
			} else if value.Valid {
				c.NumberOfDefeats = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Champ.
// Note that you need to call Champ.Unwrap() before calling this method if this Champ
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Champ) Update() *ChampUpdateOne {
	return (&ChampClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Champ entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Champ) Unwrap() *Champ {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Champ is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Champ) String() string {
	var builder strings.Builder
	builder.WriteString("Champ(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", name=")
	builder.WriteString(c.Name)
	builder.WriteString(", path=")
	builder.WriteString(c.Path)
	builder.WriteString(", number_of_victory=")
	builder.WriteString(fmt.Sprintf("%v", c.NumberOfVictory))
	builder.WriteString(", number_of_defeats=")
	builder.WriteString(fmt.Sprintf("%v", c.NumberOfDefeats))
	builder.WriteByte(')')
	return builder.String()
}

// Champs is a parsable slice of Champ.
type Champs []*Champ

func (c Champs) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
