// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Corewar_Api/ent/champ"
	"Corewar_Api/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	champFields := schema.Champ{}.Fields()
	_ = champFields
	// champDescName is the schema descriptor for name field.
	champDescName := champFields[1].Descriptor()
	// champ.NameValidator is a validator for the "name" field. It is called by the builders before save.
	champ.NameValidator = champDescName.Validators[0].(func(string) error)
	// champDescPath is the schema descriptor for path field.
	champDescPath := champFields[2].Descriptor()
	// champ.PathValidator is a validator for the "path" field. It is called by the builders before save.
	champ.PathValidator = champDescPath.Validators[0].(func(string) error)
	// champDescNumberOfVictory is the schema descriptor for number_of_victory field.
	champDescNumberOfVictory := champFields[3].Descriptor()
	// champ.DefaultNumberOfVictory holds the default value on creation for the number_of_victory field.
	champ.DefaultNumberOfVictory = champDescNumberOfVictory.Default.(int)
	// champ.NumberOfVictoryValidator is a validator for the "number_of_victory" field. It is called by the builders before save.
	champ.NumberOfVictoryValidator = champDescNumberOfVictory.Validators[0].(func(int) error)
	// champDescNumberOfDefeats is the schema descriptor for number_of_defeats field.
	champDescNumberOfDefeats := champFields[4].Descriptor()
	// champ.DefaultNumberOfDefeats holds the default value on creation for the number_of_defeats field.
	champ.DefaultNumberOfDefeats = champDescNumberOfDefeats.Default.(int)
	// champ.NumberOfDefeatsValidator is a validator for the "number_of_defeats" field. It is called by the builders before save.
	champ.NumberOfDefeatsValidator = champDescNumberOfDefeats.Validators[0].(func(int) error)
	// champDescID is the schema descriptor for id field.
	champDescID := champFields[0].Descriptor()
	// champ.DefaultID holds the default value on creation for the id field.
	champ.DefaultID = champDescID.Default.(func() uuid.UUID)
}
