// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChampsColumns holds the columns for the "champs" table.
	ChampsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "number_of_victory", Type: field.TypeInt, Default: 0},
		{Name: "number_of_defeats", Type: field.TypeInt, Default: 0},
	}
	// ChampsTable holds the schema information for the "champs" table.
	ChampsTable = &schema.Table{
		Name:        "champs",
		Columns:     ChampsColumns,
		PrimaryKey:  []*schema.Column{ChampsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChampsTable,
	}
)

func init() {
}
